-- PostgreSQL initialization for Vertical Climbing MVP
-- This script mirrors the current SQLAlchemy models used by the backend.

CREATE TABLE IF NOT EXISTS clients (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    accepted_terms BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_clients_age CHECK (birth_date <= CURRENT_DATE - INTERVAL '18 years')
);

CREATE TABLE IF NOT EXISTS instructors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    specialization VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS training_formats (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    level VARCHAR(50) NOT NULL,
    description TEXT
);

CREATE TABLE IF NOT EXISTS zones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    max_capacity INTEGER NOT NULL DEFAULT 16,
    CONSTRAINT ck_zones_capacity CHECK (max_capacity > 0)
);

CREATE TABLE IF NOT EXISTS slots (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    capacity INTEGER NOT NULL,
    available_spots INTEGER NOT NULL,
    instructor_name VARCHAR(255) NOT NULL,
    format_name VARCHAR(100) NOT NULL,
    zone_name VARCHAR(100),
    price INTEGER,
    status VARCHAR(50) NOT NULL DEFAULT 'scheduled',
    CONSTRAINT ck_slots_capacity CHECK (capacity > 0),
    CONSTRAINT ck_slots_available_spots CHECK (available_spots >= 0 AND available_spots <= capacity),
    CONSTRAINT ck_slots_status CHECK (status IN ('scheduled', 'cancelled', 'cancelled_by_gym'))
);

CREATE TABLE IF NOT EXISTS bookings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NOT NULL REFERENCES clients(id),
    slot_id INTEGER NOT NULL REFERENCES slots(id),
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    booked_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_bookings_status CHECK (status IN ('pending', 'confirmed', 'cancelled', 'cancelled_by_gym'))
);

CREATE TABLE IF NOT EXISTS equipment_rentals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INTEGER NOT NULL UNIQUE REFERENCES bookings(id) ON DELETE CASCADE,
    use_rental BOOLEAN NOT NULL DEFAULT FALSE,
    rental_price NUMERIC(10, 2) NOT NULL DEFAULT 0,
    CONSTRAINT ck_rental_price CHECK (
        (use_rental = FALSE AND rental_price = 0)
        OR
        (use_rental = TRUE AND rental_price > 0)
    )
);

CREATE TABLE IF NOT EXISTS instructor_ratings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INTEGER NOT NULL UNIQUE REFERENCES bookings(id) ON DELETE CASCADE,
    score INTEGER NOT NULL CHECK (score BETWEEN 1 AND 5),
    review_text TEXT
);

CREATE TABLE IF NOT EXISTS info_pages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_slots_start_time ON slots(start_time);
CREATE INDEX IF NOT EXISTS idx_bookings_client_id ON bookings(client_id);
CREATE INDEX IF NOT EXISTS idx_bookings_slot_id ON bookings(slot_id);
